<?php

/**
 * Baseregione
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nome
 * @property provincia $regione
 * 
 * @method string    getNome()    Returns the current record's "nome" value
 * @method provincia getRegione() Returns the current record's "regione" value
 * @method regione   setNome()    Sets the current record's "nome" value
 * @method regione   setRegione() Sets the current record's "regione" value
 * 
 * @package    transfer
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Baseregione extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('regione');
        $this->hasColumn('nome', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('provincia as regione', array(
             'local' => 'id',
             'foreign' => 'regione_id'));
    }
}