<?php

/**
 * Baselocality
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property bigint $address_id
 * @property boolean $is_vector
 * @property address $Address
 * @property locality_contact $locality_contact
 * @property locality_social $locality_social
 * @property Doctrine_Collection $locality_from
 * @property Doctrine_Collection $locality_to
 * 
 * @method string              getName()             Returns the current record's "name" value
 * @method bigint              getAddressId()        Returns the current record's "address_id" value
 * @method boolean             getIsVector()         Returns the current record's "is_vector" value
 * @method address             getAddress()          Returns the current record's "Address" value
 * @method locality_contact    getLocalityContact()  Returns the current record's "locality_contact" value
 * @method locality_social     getLocalitySocial()   Returns the current record's "locality_social" value
 * @method Doctrine_Collection getLocalityFrom()     Returns the current record's "locality_from" collection
 * @method Doctrine_Collection getLocalityTo()       Returns the current record's "locality_to" collection
 * @method locality            setName()             Sets the current record's "name" value
 * @method locality            setAddressId()        Sets the current record's "address_id" value
 * @method locality            setIsVector()         Sets the current record's "is_vector" value
 * @method locality            setAddress()          Sets the current record's "Address" value
 * @method locality            setLocalityContact()  Sets the current record's "locality_contact" value
 * @method locality            setLocalitySocial()   Sets the current record's "locality_social" value
 * @method locality            setLocalityFrom()     Sets the current record's "locality_from" collection
 * @method locality            setLocalityTo()       Sets the current record's "locality_to" collection
 * 
 * @package    transfer
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Baselocality extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('locality');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('address_id', 'bigint', null, array(
             'type' => 'bigint',
             ));
        $this->hasColumn('is_vector', 'boolean', null, array(
             'type' => 'boolean',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('address as Address', array(
             'local' => 'address_id',
             'foreign' => 'id'));

        $this->hasOne('locality_contact', array(
             'local' => 'id',
             'foreign' => 'locality_id'));

        $this->hasOne('locality_social', array(
             'local' => 'id',
             'foreign' => 'locality_id'));

        $this->hasMany('transfer as locality_from', array(
             'local' => 'id',
             'foreign' => 'locality_from'));

        $this->hasMany('transfer as locality_to', array(
             'local' => 'id',
             'foreign' => 'locality_to'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}