<?php

/**
 * Baselocality_contact
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property bigint $licality_id
 * @property bigint $contact_id
 * @property string $value
 * @property locality $Locality
 * 
 * @method bigint           getLicalityId()  Returns the current record's "licality_id" value
 * @method bigint           getContactId()   Returns the current record's "contact_id" value
 * @method string           getValue()       Returns the current record's "value" value
 * @method locality         getLocality()    Returns the current record's "Locality" value
 * @method locality_contact setLicalityId()  Sets the current record's "licality_id" value
 * @method locality_contact setContactId()   Sets the current record's "contact_id" value
 * @method locality_contact setValue()       Sets the current record's "value" value
 * @method locality_contact setLocality()    Sets the current record's "Locality" value
 * 
 * @package    transfer
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Baselocality_contact extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('locality_contact');
        $this->hasColumn('licality_id', 'bigint', null, array(
             'type' => 'bigint',
             ));
        $this->hasColumn('contact_id', 'bigint', null, array(
             'type' => 'bigint',
             ));
        $this->hasColumn('value', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('locality as Locality', array(
             'local' => 'locality_id',
             'foreign' => 'id'));
    }
}