<?php

/**
 * Baseprovincia
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nome
 * @property bigint $regione_id
 * @property string $sigla
 * @property regione $Regione
 * @property comune $provincia
 * 
 * @method string    getNome()       Returns the current record's "nome" value
 * @method bigint    getRegioneId()  Returns the current record's "regione_id" value
 * @method string    getSigla()      Returns the current record's "sigla" value
 * @method regione   getRegione()    Returns the current record's "Regione" value
 * @method comune    getProvincia()  Returns the current record's "provincia" value
 * @method provincia setNome()       Sets the current record's "nome" value
 * @method provincia setRegioneId()  Sets the current record's "regione_id" value
 * @method provincia setSigla()      Sets the current record's "sigla" value
 * @method provincia setRegione()    Sets the current record's "Regione" value
 * @method provincia setProvincia()  Sets the current record's "provincia" value
 * 
 * @package    transfer
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Baseprovincia extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('provincia');
        $this->hasColumn('nome', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('regione_id', 'bigint', null, array(
             'type' => 'bigint',
             ));
        $this->hasColumn('sigla', 'string', 4, array(
             'type' => 'string',
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('regione as Regione', array(
             'local' => 'regione_id',
             'foreign' => 'id'));

        $this->hasOne('comune as provincia', array(
             'local' => 'id',
             'foreign' => 'provincia_id'));
    }
}