<?php

/**
 * Basevehicle
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property bigint $vehicle_type_id
 * @property string $name
 * @property string $plate
 * @property string $serial
 * @property integer $km
 * @property integer $anno
 * @property string $note
 * @property vehicleType $VehicleType
 * @property Doctrine_Collection $vehicle_transfer
 * 
 * @method bigint              getVehicleTypeId()    Returns the current record's "vehicle_type_id" value
 * @method string              getName()             Returns the current record's "name" value
 * @method string              getPlate()            Returns the current record's "plate" value
 * @method string              getSerial()           Returns the current record's "serial" value
 * @method integer             getKm()               Returns the current record's "km" value
 * @method integer             getAnno()             Returns the current record's "anno" value
 * @method string              getNote()             Returns the current record's "note" value
 * @method vehicleType         getVehicleType()      Returns the current record's "VehicleType" value
 * @method Doctrine_Collection getVehicleTransfer()  Returns the current record's "vehicle_transfer" collection
 * @method vehicle             setVehicleTypeId()    Sets the current record's "vehicle_type_id" value
 * @method vehicle             setName()             Sets the current record's "name" value
 * @method vehicle             setPlate()            Sets the current record's "plate" value
 * @method vehicle             setSerial()           Sets the current record's "serial" value
 * @method vehicle             setKm()               Sets the current record's "km" value
 * @method vehicle             setAnno()             Sets the current record's "anno" value
 * @method vehicle             setNote()             Sets the current record's "note" value
 * @method vehicle             setVehicleType()      Sets the current record's "VehicleType" value
 * @method vehicle             setVehicleTransfer()  Sets the current record's "vehicle_transfer" collection
 * 
 * @package    transfer
 * @subpackage model
 * @author     poldotz
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basevehicle extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('vehicle');
        $this->hasColumn('vehicle_type_id', 'bigint', null, array(
             'type' => 'bigint',
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('plate', 'string', 10, array(
             'type' => 'string',
             'length' => 10,
             ));
        $this->hasColumn('serial', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('km', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('anno', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('note', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('vehicleType as VehicleType', array(
             'local' => 'vehicle_type_id',
             'foreign' => 'id'));

        $this->hasMany('Arrival as vehicle_transfer', array(
             'local' => 'id',
             'foreign' => 'vehicle_id'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($sluggable0);
        $this->actAs($timestampable0);
    }
}