<?php

/**
 * Baselocality_social
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property bigint $locality_id
 * @property bigint $social_id
 * @property string $value
 * @property locality $Locality
 * 
 * @method bigint          getLocalityId()  Returns the current record's "locality_id" value
 * @method bigint          getSocialId()    Returns the current record's "social_id" value
 * @method string          getValue()       Returns the current record's "value" value
 * @method locality        getLocality()    Returns the current record's "Locality" value
 * @method locality_social setLocalityId()  Sets the current record's "locality_id" value
 * @method locality_social setSocialId()    Sets the current record's "social_id" value
 * @method locality_social setValue()       Sets the current record's "value" value
 * @method locality_social setLocality()    Sets the current record's "Locality" value
 * 
 * @package    transfer
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Baselocality_social extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('locality_social');
        $this->hasColumn('locality_id', 'bigint', null, array(
             'type' => 'bigint',
             ));
        $this->hasColumn('social_id', 'bigint', null, array(
             'type' => 'bigint',
             ));
        $this->hasColumn('value', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('locality as Locality', array(
             'local' => 'locality_id',
             'foreign' => 'id'));
    }
}