<?php

/**
 * BasepayMethod
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $pay_method_transfer
 * 
 * @method string              getName()                Returns the current record's "name" value
 * @method Doctrine_Collection getPayMethodTransfer()   Returns the current record's "pay_method_transfer" collection
 * @method payMethod           setName()                Sets the current record's "name" value
 * @method payMethod           setPayMethodTransfer()   Sets the current record's "pay_method_transfer" collection
 * 
 * @package    transfer
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasepayMethod extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pay_method');
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Arrival as pay_method_transfer', array(
             'local' => 'id',
             'foreign' => 'pay_method_id'));
    }
}