<?php

/**
 * Basecomune
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nome
 * @property bigint $provincia_id
 * @property provincia $Provincia
 * 
 * @method string    getNome()         Returns the current record's "nome" value
 * @method bigint    getProvinciaId()  Returns the current record's "provincia_id" value
 * @method provincia getProvincia()    Returns the current record's "Provincia" value
 * @method comune    setNome()         Sets the current record's "nome" value
 * @method comune    setProvinciaId()  Sets the current record's "provincia_id" value
 * @method comune    setProvincia()    Sets the current record's "Provincia" value
 * 
 * @package    transfer
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basecomune extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('comune');
        $this->hasColumn('nome', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('provincia_id', 'bigint', null, array(
             'type' => 'bigint',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('provincia as Provincia', array(
             'local' => 'provincia_id',
             'foreign' => 'id'));
    }
}