<?php

/**
 * BasetransportationType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $min
 * @property integer $max
 * 
 * @method string             getName() Returns the current record's "name" value
 * @method integer            getMin()  Returns the current record's "min" value
 * @method integer            getMax()  Returns the current record's "max" value
 * @method transportationType setName() Sets the current record's "name" value
 * @method transportationType setMin()  Sets the current record's "min" value
 * @method transportationType setMax()  Sets the current record's "max" value
 * 
 * @package    transfer
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasetransportationType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('transportation_type');
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('min', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('max', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $this->actAs($sluggable0);
    }
}