<?php

/**
 * Basecustomers
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property bigint $sf_guard_user_id
 * @property bigint $contact_id
 * @property sfGuardUser $User
 * 
 * @method bigint      getSfGuardUserId()    Returns the current record's "sf_guard_user_id" value
 * @method bigint      getContactId()        Returns the current record's "contact_id" value
 * @method sfGuardUser getUser()             Returns the current record's "User" value
 * @method customers   setSfGuardUserId()    Sets the current record's "sf_guard_user_id" value
 * @method customers   setContactId()        Sets the current record's "contact_id" value
 * @method customers   setUser()             Sets the current record's "User" value
 * 
 * @package    transfer
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basecustomers extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('customers');
        $this->hasColumn('sf_guard_user_id', 'bigint', null, array(
             'type' => 'bigint',
             ));
        $this->hasColumn('contact_id', 'bigint', null, array(
             'type' => 'bigint',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'sf_guard_user_id',
             'foreign' => 'id'));
    }
}