<?php

/**
 * ArrivalTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ArrivalTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ArrivalTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Arrival');
    }
}