<?php

/**
 * bookingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class bookingTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object bookingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('booking');
    }
}