<?php

/**
 * companyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class companyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object companyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('company');
    }
}