<?php

/**
 * comuneTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class comuneTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object comuneTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('comune');
    }
}