<?php

/**
 * configurationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class configurationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object configurationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('configuration');
    }
}