<?php

/**
 * contactTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class contactTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object contactTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('contact');
    }
}