<?php

/**
 * customersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class customersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object customersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('customers');
    }
}