<?php

/**
 * DepartureTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DepartureTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DepartureTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Departure');
    }
}