<?php

/**
 * flightTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class flightTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object flightTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('flight');
    }
}