<?php

/**
 * locality_socialTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class locality_socialTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object locality_socialTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('locality_social');
    }
}