<?php

/**
 * locality_contactTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class locality_contactTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object locality_contactTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('locality_contact');
    }
}