<?php

/**
 * localityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class localityTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object localityTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('locality');
    }
}