<?php

/**
 * payMethodTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class payMethodTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object payMethodTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('payMethod');
    }
}