<?php

/**
 * regioneTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class regioneTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object regioneTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('regione');
    }
}