<?php

/**
 * socialTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class socialTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object socialTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('social');
    }
}