<?php

/**
 * transportation_typeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class transportation_typeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object transportation_typeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('transportation_type');
    }
}