<?php

/**
 * transportationTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class transportationTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object transportationTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('transportationType');
    }
}