<?php

/**
 * transferTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class transferTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object transferTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('transfer');
    }
}