<?php

/**
 * user_socialTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class user_socialTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object user_socialTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('user_social');
    }
}