<?php

/**
 * user_contactTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class user_contactTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object user_contactTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('user_contact');
    }
}