<?php

/**
 * vectorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class vectorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object vectorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('vector');
    }
}