<?php

/**
 * vector_typeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class vector_typeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object vector_typeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('vector_type');
    }
}