<?php

/**
 * vehicleTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class vehicleTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object vehicleTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('vehicleType');
    }
}