<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/02/14 15:51:32

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=transferplus',
  'username' => 'root',
  'password' => 'lpodda',
  'name' => 'doctrine',
)),);
