<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/08/28 00:27:14

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=transferplus',
  'username' => 'root',
  'password' => 'lpodda',
  'name' => 'doctrine',
)),);
