<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/11/29 16:39:59

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'DebugPDO',
  'dsn' => 'mysql:host=localhost;dbname=transferplus',
  'username' => 'root',
  'password' => 'lpodda',
  'encoding' => NULL,
  'persistent' => true,
  'pooling' => true,
  'queries' => 
  array (
    'value' => 'SET NAMES UTF8;',
  ),
  'debug' => 
  array (
    'realmemoryusage' => true,
    'details' => 
    array (
      'time' => 
      array (
        'enabled' => true,
      ),
      'slow' => 
      array (
        'enabled' => true,
        'threshold' => 0.1,
      ),
      'mem' => 
      array (
        'enabled' => true,
      ),
      'mempeak' => 
      array (
        'enabled' => true,
      ),
      'memdelta' => 
      array (
        'enabled' => true,
      ),
    ),
  ),
  'name' => 'propel',
)),);
