detect_relations: true
regione:
  columns:
    nome:
      type: string(50)
provincia:
  columns:
    nome:
      type: string(20)
    regione_id:
      type: bigint
    sigla:
      type: string(4)
  relations:
    Regione:
      class: regione
      foreignType: one
      local: regione_id
      foreign: id
      foreignAlias: regione
comune:
  columns:
    nome:
      type: string(255)
    provincia_id:
      type: bigint
  relations:
    Provincia:
      class: provincia
      foreignType: one
      local: provincia_id
      foreign: id
      foreignAlias: provincia
address:
  actAs: [Geographical]
  columns:
    route:
      type: string(255)
    city:
      type: string(100)
    province:
      type: string(100)
    region:
      type: string(100)
    country:
      type:  string(100)
    postal_code:
      type:  string(10)
    latitude:
      type: decimal(18)
      scale: 2
    longitude:
      type: decimal(18)
      scale: 2
contact:
  columns:
    name:
      type: string(100)
social:
  columns:
    name:
      type: string(100)
configuration:
  columns:
    name:
      type: string(100)
    value:
      type: string(255)
user_contact:
  columns:
    sf_guard_user_id: bigint
    contact_id: bigint
    value: string(255)
  relations:
    User:
      class: sfGuardUser
      foreignType: one
      local: sf_guard_user_id
      foreign: id
      foreignAlias: user_contact
    Social:
      class: Contact
      foreignType: one
      local: contact_id
      foreign: id
      foreignAlias: contact_user
user_social:
  columns:
    sf_guard_user_id: bigint
    social_id: bigint
    value:     type: string(255)
  relations:
    User:
      class: sfGuardUser
      foreignType: one
      local: sf_guard_user_id
      foreign: id
      foreignAlias: user_social
    Social:
      class: Social
      foreignType: one
      local: social_id
      foreign: id
      foreignAlias: social_user
company:
  actAs:
    Timestampable:
    Sluggable:
      fields: [name,description]
  columns:
    name:
      type: string(100)
      notnull: true
    description:
      type: string(100)
    vat:
      type: string(11)
      notnull: true
    address_id: bigint
  relations:
    Address:
      class: address
      foreignType: one
      local: address_id
      foreign: id
      foreignAlias: company_address
vehicleType:
  actAs:
    Sluggable:
      fields: [name]
  columns:
    name: string(100)
    min: integer
    max: integer
vehicle:
  actAs:
    Sluggable:
      fields: [name]
    Timestampable:
  columns:
    vehicle_type_id: bigint
    name: string(100)
    plate: string(10)
    serial: string(100)
    km: integer
    anno: integer
    note: string(255)
  relations:
    VehicleType:
      class: vehicleType
      foreignType: one
      local: vehicle_type_id
      foreign: id
      foreignAlias: vehicle_type
booking:
  actAs:
    Blameable:
    Timestampable:
    SoftDelete:
    Versionable:
      versionColumn: version
      className: %CLASS%Version
      auditLog: true
  columns:
    booking_date:
      type: datetime
    year:
      type: integer
    number:
      type: integer
    adult:
      type: integer
    child:
      type: integer
    contact:
      type: string(100)
    rif_file:
      type: string(100)
    customer_id:
      type: integer
    vehicle_type_id:
      type: bigint
    is_confirmed:
      type: boolean
      default: false
  relations:
    User:
      class: sfGuardUser
      foreignType: one
      local: customer_id
      foreign: id
      foreignAlias: customer_book
    VehicleType:
      class: vehicleType
      foreignType: one
      local: vehicle_type_id
      foreign: id
      foreignAlias: vehicle_type_book
  indexes:
    unique_index:
      fields: [year,number]
      type: unique
locality:
  actAs:
    Timestampable:
    Sluggable:
      fields: [name]
  columns:
    name:
      type: string(255)
    address_id: bigint
    is_vector:
      type: boolean
  relations:
    Address:
      class: address
      foreignType: one
      local: address_id
      foreign: id
      foreignAlias: locality_address
locality_contact:
  columns:
    locality_id: bigint
    contact_id: bigint
    value: string(255)
  relations:
    Locality:
      class: locality
      foreignType: one
      local: locality_id
      foreign: id
      foreignAlias: locality_contact
    Social:
      class: Contact
      foreignType: one
      local: contact_id
      foreign: id
      foreignAlias: contact_locality
locality_social:
  columns:
    locality_id: bigint
    social_id: bigint
    value:     type: string(255)
  relations:
    Locality:
      class: locality
      foreignType: one
      local: locality_id
      foreign: id
      foreignAlias: locality_social
    Social:
      class: Social
      foreignType: one
      local: social_id
      foreign: id
      foreignAlias: social_locality
payMethod:
  columns:
    name: string(100)
Arrival:
  actAs:
    Blameable:
    Timestampable:
    SoftDelete:
    Versionable:
      versionColumn: version
      className: %CLASS%Version
      auditLog: true
  columns:
    booking_id:
      type: bigint
      primary: true
    day:
      type: date
    hour:
      type: time
    flight: string(10)
    cost:
      type: decimal(5)
      scale: 2
    note:
      type: string(255)
    locality_from: bigint
    locality_to: bigint
    driver_id: bigint
    vehicle_id: bigint
    pay_method_id: bigint
  relations:
    LocalityFrom:
      class: locality
      local: locality_from
      foreign: id
      foreignAlias: locality_from
    Booking:
      class: booking
      local: booking_id
      foreign: id
      foreignAlias: arrival_booking
    LocalityTo:
       class: locality
       local: locality_to
       foreign: id
       foreignAlias: locality_to
    Driver:
      class: sfGuardUser
      local: driver_id
      foreign: id
      foreignAlias: driver_transfer
    Vehicle:
      class: vehicle
      local: vehicle_id
      foreign: id
      foreignAlias: vehicle_transfer
    PayMethod:
      class: payMethod
      local: pay_method_id
      foreign: id
      foreignAlias: pay_method_transfer
Departure:
  actAs:
    Blameable:
    Timestampable:
    SoftDelete:
    Versionable:
      versionColumn: version
      className: %CLASS%Version
      auditLog: true
  columns:
    booking_id:
      type: bigint
      primary: true
    day:
      type: date
    hour:
      type: time
    departure_time:
      type: time
    pick_up:
      type: boolean
    flight: string(10)
    cost:
      type: decimal(5)
      scale: 2
    note:
      type: string(255)
    locality_from: bigint
    locality_to: bigint
    driver_id: bigint
    vehicle_id: bigint
    pay_method_id: bigint
  relations:
    Booking:
      class: booking
      local: booking_id
      foreign: id
      foreignAlias: departure_booking
    LocalityFrom:
      class: locality
      local: locality_from
      foreign: id
      foreignAlias: locality_from
    LocalityTo:
       class: locality
       local: locality_to
       foreign: id
       foreignAlias: locality_to
    Driver:
      class: sfGuardUser
      local: driver_id
      foreign: id
      foreignAlias: driver_transfer
    Vehicle:
      class: vehicle
      local: vehicle_id
      foreign: id
      foreignAlias: vehicle_transfer
    PayMethod:
      class: payMethod
      local: pay_method_id
      foreign: id
      foreignAlias: pay_method_transfer
vector_type:
  columns:
    name: string(100)
vector:
  columns:
    code: string(100)
    vector_type_id: bigint
    locality_id: bigint
  relations:
    VectorType:
      class: VectoryType
      local: vectory_type_id
      foreign: id
      foreignAlias: vector_type
    Locality:
       class: locality
       local: locality_id
       foreign: id
       foreignAlias: locality_vector
Carrier:
  columns:
    code: string(10)
    name: string(100)
flight:
  columns:
    code: string(10)
    valid_from:
      type: date
    valid_to:
      type: date
    departure: time
    arrival: time
    days: integer
    carrier_id: bigint
  relations:
    Carrier:
      class: Carrier
      local: carrier_id
      foreign: id
      foreignAlias: flight_carrier