detect_relations: true

regione:
  columns:
    nome:
      type: string(50)
provincia:
  columns:
    nome:
      type: string(20)
    regione_id:
      type: bigint
    sigla:
      type: string(4)
  relations:
    Regione:
      class: regione
      foreignType: one
      local: regione_id
      foreign: id
      foreignAlias: regione
comune:
  columns:
    nome:
      type: string(255)
    provincia_id:
      type: bigint
  relations:
    Provincia:
      class: provincia
      foreignType: one
      local: provincia_id
      foreign: id
      foreignAlias: provincia
address:
  columns:
    route:
      type: string(255)
    city:
      type: string(100)
    province:
      type: string(100)
    region:
      type: string(100)
    country:
      type:  string(100)
    postal_code:
      type:  string(10)
    latitude:
      type: decimal(18)
      scale: 2
    longitude:
      type: decimal(18)
      scale: 2
contact:
  columns:
    name:
      type: string(100)
    value:
      type: string(255)
social:
  columns:
    name:
      type: string(100)
    value:
      type: string(255)
configuration:
  columns:
    name:
      type: string(100)
    value:
      type: string(255)
user_contact:
  columns:
    sf_guard_user_id: bigint
    contact_id: bigint
  relations:
    User:
      class: sfGuardUser
      foreignType: one
      local: sf_guard_user_id
      foreign: id
      foreignAlias: user_contact
    Social:
      class: Contact
      foreignType: one
      local: contact_id
      foreign: id
      foreignAlias: contact_user
user_social:
  columns:
    sf_guard_user_id: bigint
    social_id: bigint
  relations:
    User:
      class: sfGuardUser
      foreignType: one
      local: sf_guard_user_id
      foreign: id
      foreignAlias: user_social
    Social:
      class: Social
      foreignType: one
      local: social_id
      foreign: id
      foreignAlias: social_user
company:
  actAs:
    Timestampable:
    Sluggable:
      fields: [name,description]
  columns:
    name:
      type: string(100)
      notnull: true
    description:
      type: string(100)
    vat:
      type: string(11)
      notnull: true
    address_id: bigint
  relations:
    Address:
      class: address
      foreignType: one
      local: address_id
      foreign: id
      foreignAlias: company_address

vehicleType:
  actAs:
    Sluggable:
      fields: [name]
  columns:
    name: string(100)
    min: integer
    max: integer
vehicle:
  actAs:
    Sluggable:
      fields: [name]
    Timestampable:
  columns:
    vehicle_type_id: bigint
    name: string(100)
    plate: string(10)
    serial: string(100)
    km: integer
    anno: integer
    note: string(255)
  relations:
    vehicleType:
      class: vehicleType
      foreignType: one
      local: vehicle_type_id
      foreign: id
      foreignAlias: trasportation_type
booking:
  actAs:
    Blameable:
    Timestampable:
    SoftDelete:
  columns:
    booking_date:
      type: datetime
    year:
      type: integer
    number:
      type: integer
    adult:
      type: integer
    child:
      type: integer
    contact:
      type: string(100)
    rif_file:
      type: string(100)
    customer_id:
      type: integer
  relations:
    User:
      class: sfGuardUser
      foreignType: one
      local: customer_id
      foreign: id
      foreignAlias: customer_book
  indexes:
    unique_index:
      fields: [year,number]
      type: unique